-- NOTE: THIS IS AUTO GENERATED BY MATUGEN. CHANGES CAN AND WILL BE OVERWRITTEN
-- colors.lua

local color_scheme = {
	foreground = "{{colors.on_surface.default.hex}}",
	background = "{{colors.background.default.hex}}",

	cursor_bg = "{{colors.primary.default.hex}}",
	cursor_fg = "{{colors.on_primary.default.hex}}",
	cursor_border = "{{colors.primary.default.hex}}",

	selection_fg = "{{colors.on_primary.default.hex}}",
	selection_bg = "{{colors.primary.default.hex}}",

	scrollbar_thumb = "{{colors.surface_variant.default.hex}}",

	split = "{{colors.outline.default.hex}}",

	ansi = {
		"#181818",
		"{{colors.error.default.hex}}",
		"{{colors.primary.default.hex}}",
		"{{colors.inverse_primary.default.hex}}",
		"{{colors.primary.default.hex}}",
		"{{colors.tertiary.default.hex}}",
		"{{colors.secondary.default.hex}}",
		"#BAC2DE",
	},
	brights = {
		"#585B70",
		"#F38BA8",
		"#A6E3A1",
		"#F9E2AF",
		"#89B4FA",
		"#F5C2E7",
		"#94E2D5",
		"#A6ADC8",
	},

	indexed = { [136] = "{{colors.tertiary.default.hex}}" },
	compose_cursor = "{{colors.secondary.default.hex}}",
	copy_mode_active_highlight_bg = { Color = "{{colors.background.default.hex}}" },
	copy_mode_active_highlight_fg = { AnsiColor = "Black" },
	copy_mode_inactive_highlight_bg = { Color = "{{colors.primary.default.hex}}" },
	copy_mode_inactive_highlight_fg = { AnsiColor = "White" },

	quick_select_label_bg = { Color = "{{colors.secondary.default.hex}}" },
	quick_select_label_fg = { Color = "{{colors.on_secondary.default.hex}}" },
	quick_select_match_bg = { AnsiColor = "Navy" },
	quick_select_match_fg = { Color = "{{colors.on_surface.default.hex}}" },

	input_selector_label_bg = { AnsiColor = "Black" },
	input_selector_label_fg = { Color = "{{colors.on_surface.default.hex}}" },

	launcher_label_bg = { AnsiColor = "Black" },
	launcher_label_fg = { Color = "{{colors.on_surface.default.hex}}" },

	tab_bar = {
		background = "{{colors.surface.default.hex}}",

		active_tab = {
			bg_color = "{{colors.surface_container_high.default.hex}}",
			fg_color = "{{colors.on_surface.default.hex}}",
			intensity = "Normal",
			underline = "None",
			italic = false,
			strikethrough = false,
		},

		inactive_tab = {
			bg_color = "{{colors.surface_container.default.hex}}",
			fg_color = "{{colors.on_surface_variant.default.hex}}",
		},

		inactive_tab_hover = {
			bg_color = "{{colors.surface_container_highest.default.hex}}",
			fg_color = "{{colors.on_surface.default.hex}}",
			italic = true,
		},

		new_tab = {
			bg_color = "{{colors.surface_container.default.hex}}",
			fg_color = "{{colors.on_surface_variant.default.hex}}",
		},

		new_tab_hover = {
			bg_color = "{{colors.surface_container_highest.default.hex}}",
			fg_color = "{{colors.on_surface.default.hex}}",
			italic = true,
		},

		inactive_tab_edge = "{{colors.outline.default.hex}}",
	},
}

local window_frame = {
	active_titlebar_bg = "{{colors.background.default.hex}}",
	inactive_titlebar_bg = "{{colors.background.default.hex}}",
}

return { color_scheme = color_scheme, window_frame = window_frame }
